export const CONTRACTORS = [
  "PST",
  "Zlal Arabia",
  "Stone Link",
  "Safwat Tafaseel",
  "Station",
  "Rbco",
  "Smnan",
  "Dar Alabda",
  "Major",
  "X-SAB",
  "Tamear",
] as const;

export const LOCATIONS = [
  ...Array.from({ length: 12 }, (_, i) => `Cluster ${String(i + 1).padStart(2, "0")}`),
  ...Array.from({ length: 6 }, (_, i) => `Building ${String(i + 1).padStart(2, "0")}`),
  "Club house",
  "Sitewide",
  "Basement 01",
  "Basement 02",
  "Swimmingpool",
  "Office area",
  "Welfare facilites",
  "Retail 01",
  "Retail 02",
  "Retail 03",
] as const;

export const CATEGORIES = [
  "Work at Height",
  "Scaffolding",
  "Ladders",
  "Slips / Trips / Falls",
  "PPE",
  "Housekeeping",
  "Electrical",
  "Power Tools",
  "Hand Tools",
  "Hot Works",
  "Fire Safety",
  "Excavations",
  "Gas Cylinders",
  "Lifting Equipment",
  "Lifting Operations",
  "Confined Space",
  "Temporary Works",
  "Traffic Management",
  "Manual Handling",
  "Noise",
  "Vibration",
  "Lighting",
  "Welfare",
  "Environment",
  "Emergency Response",
  "Health / Heat Stress",
  "Falling Objects",
  "Storage",
  "Hazardous Substances",
  "Supervision",
  "Training / Competence",
  "Signage",
  "Access / Egress",
  "Security",
  "Barriers/ edge Protaction",
  "Other",
] as const;

export const ASSIGNED_TO = [
  "M.Alharbi",
  "Jasim",
  "Raja",
  "Ejaz",
  "Majed",
  "M.Alshamri",
  "Gul",
  "Habib",
  "Zayed",
] as const;

export const RISK_LEVELS = ["High", "Medium", "Low"] as const;
export const STATUSES = ["Open", "Close"] as const;
